version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sqlitedb-app
    ports:
      - "8080:8080"  
    volumes:
      - ./user.db:/app/user.db  
    environment:
      - SPRING_PROFILES_ACTIVE=prod  
    restart: unless-stopped 

